import * as XLSX from 'xlsx';
import { Semester, UserProfile } from '../types';

/**
 * Exports all semesters academic data to a formatted Excel workbook.
 */
export const exportToExcel = (semesters: Semester[], profile: UserProfile | null) => {
  if (!profile) return;

  const workbook = XLSX.utils.book_new();

  // 1. Overall Summary Sheet
  const summaryData = [
    ['GradeVault Academic Summary'],
    [],
    ['Student Name', profile.name],
    ['Student Email', profile.email],
    ['Joined Date', new Date(profile.createdAt).toLocaleDateString()],
    [],
    ['Academic Metrics'],
    ['Cumulative CGPA', profile.cgpa.toFixed(2)],
    ['Overall Percentage', `${profile.percentage.toFixed(1)}%`],
    ['Classification', profile.classification],
    ['Credits Earned', `${profile.earnedCredits} / ${profile.totalCredits}`],
    [],
    ['Generated by GradeVault Student Academic Tracker on', new Date().toLocaleString()]
  ];

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Academic Summary');

  // 2. Semesters Sheet
  const semesterRows: any[] = [];
  
  semesters.forEach(sem => {
    semesterRows.push({
      'Semester': `Semester ${sem.semesterNumber}`,
      'Course Code': '',
      'Subject Name': '',
      'Credits': '',
      'Grade': '',
      'Earned Credit': '',
      'Semester SGPA': sem.sgpa.toFixed(2)
    });

    sem.subjects.forEach(sub => {
      semesterRows.push({
        'Semester': '',
        'Course Code': sub.courseCode,
        'Subject Name': sub.subjectName,
        'Credits': sub.credits,
        'Grade': sub.grade || 'N/A',
        'Earned Credit': sub.grade ? sub.earnedCredit : 'N/A',
        'Semester SGPA': ''
      });
    });

    // Empty row separator
    semesterRows.push({});
  });

  const semesterSheet = XLSX.utils.json_to_sheet(semesterRows);
  XLSX.utils.book_append_sheet(workbook, semesterSheet, 'Detailed Semesters');

  // Write and Save
  XLSX.writeFile(workbook, `GradeVault_Academic_Transcript_${profile.name.replace(/\s+/g, '_')}.xlsx`);
};

/**
 * Opens a print-friendly window with a styled academic transcript.
 */
export const printTranscript = (semesters: Semester[], profile: UserProfile | null) => {
  if (!profile) return;

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Pop-up blocker is preventing print view. Please allow popups.');
    return;
  }

  const semestersHTML = semesters.map(sem => `
    <div class="semester-section">
      <div class="semester-header">
        <h3>Semester ${sem.semesterNumber}</h3>
        <div>
          <span>SGPA: <strong>${sem.sgpa.toFixed(2)}</strong></span>
          <span style="margin-left: 15px;">Earned Credits: <strong>${sem.earnedCredits}</strong></span>
        </div>
      </div>
      <table>
        <thead>
          <tr>
            <th style="width: 15%;">Course Code</th>
            <th style="text-align: left;">Subject Name</th>
            <th style="width: 10%; text-align: center;">Credits</th>
            <th style="width: 10%; text-align: center;">Grade</th>
            <th style="width: 12%; text-align: center;">Earned Credit</th>
          </tr>
        </thead>
        <tbody>
          ${sem.subjects.map(sub => `
            <tr>
              <td class="font-mono">${sub.courseCode}</td>
              <td>${sub.subjectName}</td>
              <td style="text-align: center;">${sub.credits}</td>
              <td style="text-align: center; font-weight: bold;">${sub.grade || '-'}</td>
              <td style="text-align: center;">${sub.grade ? sub.earnedCredit : '-'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
  `).join('');

  printWindow.document.write(`
    <html>
      <head>
        <title>GradeVault Academic Transcript - ${profile.name}</title>
        <style>
          body {
            font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            color: #1e293b;
            padding: 40px;
            margin: 0;
            line-height: 1.5;
          }
          .header {
            text-align: center;
            border-bottom: 2px solid #16a34a;
            padding-bottom: 20px;
            margin-bottom: 30px;
          }
          .header h1 {
            margin: 0 0 5px 0;
            color: #16a34a;
            font-size: 28px;
            font-weight: 800;
          }
          .header p {
            margin: 0;
            color: #64748b;
            font-size: 14px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 1px;
          }
          .student-info {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 15px;
            margin-bottom: 30px;
            background: #f8fafc;
            padding: 20px;
            border-radius: 12px;
            border: 1px solid #e2e8f0;
          }
          .info-item {
            font-size: 14px;
          }
          .info-item strong {
            color: #475569;
          }
          .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 15px;
            margin-bottom: 40px;
          }
          .stat-card {
            background: #f0fdf4;
            border: 1px solid #bbf7d0;
            padding: 15px;
            border-radius: 12px;
            text-align: center;
          }
          .stat-card.blue {
            background: #eff6ff;
            border: 1px solid #bfdbfe;
          }
          .stat-card.indigo {
            background: #eef2ff;
            border: 1px solid #c7d2fe;
          }
          .stat-card .label {
            font-size: 10px;
            text-transform: uppercase;
            color: #64748b;
            font-weight: 700;
            letter-spacing: 0.5px;
          }
          .stat-card .val {
            font-size: 20px;
            font-weight: 800;
            color: #1e293b;
            margin-top: 5px;
          }
          .semester-section {
            margin-bottom: 35px;
            page-break-inside: avoid;
          }
          .semester-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid #e2e8f0;
            padding-bottom: 8px;
            margin-bottom: 12px;
          }
          .semester-header h3 {
            margin: 0;
            color: #1e293b;
            font-size: 16px;
            font-weight: 700;
          }
          .semester-header span {
            font-size: 13px;
            color: #475569;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
          }
          th {
            background: #f8fafc;
            color: #64748b;
            font-weight: 700;
            text-transform: uppercase;
            font-size: 9px;
            padding: 8px 12px;
            border-bottom: 1px solid #e2e8f0;
          }
          td {
            padding: 8px 12px;
            border-bottom: 1px solid #f1f5f9;
            color: #334155;
          }
          .font-mono {
            font-family: monospace;
            font-size: 11px;
            color: #64748b;
          }
          .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 11px;
            color: #94a3b8;
            border-top: 1px dashed #e2e8f0;
            padding-top: 15px;
          }
          @media print {
            body {
              padding: 0;
            }
            .no-print {
              display: none !important;
            }
          }
        </style>
      </head>
      <body>
        <div class="no-print" style="margin-bottom: 20px; text-align: right;">
          <button onclick="window.print();" style="background: #16a34a; color: white; border: none; padding: 10px 20px; border-radius: 8px; font-weight: bold; cursor: pointer;">
            Print Transcript / Save to PDF
          </button>
        </div>

        <div class="header">
          <h1>GradeVault Academic Transcript</h1>
          <p>Jawaharlal Nehru Technological University Anantapur (JNTUA)</p>
        </div>

        <div class="student-info">
          <div class="info-item"><strong>Student Name:</strong> ${profile.name}</div>
          <div class="info-item"><strong>Registered Email:</strong> ${profile.email}</div>
          <div class="info-item"><strong>Curriculum Regulation:</strong> ${profile.regulation || 'R23'} ${profile.department || 'B.Tech'}</div>
          <div class="info-item"><strong>Date Generated:</strong> ${new Date().toLocaleDateString()}</div>
        </div>

        <div class="stats-grid">
          <div class="stat-card">
            <div class="label">Cumulative CGPA</div>
            <div class="val">${profile.cgpa.toFixed(2)}</div>
          </div>
          <div class="stat-card blue">
            <div class="label">JNTUA Percentage</div>
            <div class="val">${profile.percentage.toFixed(1)}%</div>
          </div>
          <div class="stat-card indigo">
            <div class="label">Classification</div>
            <div class="val" style="font-size: 13px; font-weight: 700; margin-top: 10px;">${profile.classification}</div>
          </div>
          <div class="stat-card">
            <div class="label">Credits Completed</div>
            <div class="val">${profile.earnedCredits} / ${profile.totalCredits}</div>
          </div>
        </div>

        ${semestersHTML}

        <div class="footer">
          This transcript is generated programmatically from the student's GradeVault records. 
          Curriculum preloads conform to JNTUA R23 syllabus guidelines.
        </div>
      </body>
    </html>
  `);
  printWindow.document.close();
};
